### PR TITLE
Bump build number to sync `python.app` & `python`

### PR DESCRIPTION
**Pull request by hoechenberger**
Bump build number to ensure Python versions in `python.app` and `python` are the exact same. This is a temporary fix for #8.

cc @cbrnr

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hoechenberger** [comment]
@conda-forge-admin, please rerender

**Comment by ChrisBarker-NOAA** [comment]
The file is there (LICENSE.txt) -- just need to point the meta.yaml to it.

See staged-recipes for how to do that.

**Comment by hoechenberger** [comment]
> The file is there (LICENSE.txt) -- just need to point the meta.yaml to it.

I cannot see it in this repo, does the build script somehow retrieve it from somewhere? (couldn't find anything by quickly glancing over `build.sh`)

**Comment by hoechenberger** [comment]
To only license file in this feedstock is the one _of the feedstock_; cannot find one _of the package_ we build (i.e. inside the `recipe` dir)

**Comment by hoechenberger** [comment]
@ChrisBarker-NOAA I have copied the license file from `python-feedstock` and added it here.

**Comment by hoechenberger** [comment]
> @ChrisBarker-NOAA I have copied the license file from `python-feedstock` and added it here.

Although I'm wondering if that's correct… `python.app` was not created by the Python team, was it?

**Comment by ChrisBarker-NOAA** [comment]
No.

I'm pretty sure the original is from Anaconda.com (when it was Continuum).

But unless we can find another source for the source, not sure how we can know exactly how it's licensed.

**Comment by hoechenberger** [comment]
> I'm pretty sure the original is from Anaconda.com (when it was Continuum).

I'm pretty sure it's BSD-3 then… I've added the respective entry to the recipe. I have also added myself as a maintainer, as you suggested.

**Comment by hoechenberger** [comment]
@conda-forge-admin, please rerender

**Comment by ChrisBarker-NOAA** [comment]
OK -- LGTM.

Thanks!

Maybe time to start a discussion on the conda-forge list has to how to better handle this?

**Pull request merged**
