### PR TITLE
Use -R and not -r, as the latter follows sym-links

### LINKED ISSUE #25: python.app/Contents/MacOS/python is a copy, not a sym-link
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Howdy, I am chasing down a shared library issue, and have discovered that when `python.app` is installed into an environment, `$PREFIX/python.app/Contents/MacOS/python` ends up as a copy of `$PREFIX/bin/python`, rather than a sym-link to it.

I think this is because of the logic in `post-link.sh` - the python.app framework directory is initially installed to `$PREFIX/pythonapp`, but then in `post-link.sh` is copied to `$PREFIX/python.app` using `cp -r`.

On macOS, `cp -r` follows, rather than copies, sym-links. You can test this out yourself:

```
$ mkdir test && cd test
$ mkdir bin 
$ echo "hello" > bin/python
$ mkdir -p pythonapp/Contents/MacOS/
$ cd pythonapp/Contents/MacOS/
$ ln -s ../../../bin/python  python
$ cd ../../../
$ ls -l pythonapp/Contents/MacOS/

lrwxr-xr-x  1 paulmc  staff  19 10 Jan 12:24 python@ -> ../../../bin/python

$ cp -r pythonapp python.app
$ ls -l python.app/Contents/MacOS/python

-rw-r--r--  1 paulmc  staff  6 10 Jan 12:24 python.app/Contents/MacOS/python
```

The macOS manpage for `cp` discourages the use of `-r` for this reason, and instead
provides the `-R` option:

```
$ cp -R pythonapp python.appR
$ ls -l python.appR/Contents/MacOS/python

lrw-r--r--  1 paulmc  staff  19 10 Jan 12:25 python.appR/Contents/MacOS/python@ -> ../../../bin/python
```

So this issue can be resolved by changing `post-link.sh` to use `cp -R` instead of `cp -r.`

I'm happy to follow up with a PR if you agree. However, I'm also curious as to why the `post-link.sh` is even necessary - why does `build.sh` create `pythonapp` and not `python.app`?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
 # packages in environment at /Users/paulmc/test.env:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h0d85af4_4    conda-forge
ca-certificates           2021.10.8            h033912b_0    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libzlib                   1.2.11            h9173be1_1013    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
openssl                   3.0.0                h0d85af4_2    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
python                    3.10.1          h38b4d05_2_cpython    conda-forge
python.app                1.3             py310he24745e_6    conda-forge
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
setuptools                60.5.0                   pypi_0    pypi
sqlite                    3.37.0               h23a322b_0    conda-forge
tk                        8.6.11               h5dbffcc_1    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h9173be1_1013    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : None
       user config file : /Users/paulmc/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __osx=10.15.7=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/paulmc/miniconda3  (writable)
      conda av data dir : /Users/paulmc/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/paulmc/miniconda3/pkgs
                          /Users/paulmc/.conda/pkgs
       envs directories : /Users/paulmc/miniconda3/envs
                          /Users/paulmc/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.5 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 503:20
             netrc file : None
           offline mode : False
```
</details>

### PR DESCRIPTION
**Pull request by pauldmccarthy**
Fixes #25 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pauldmccarthy** [comment]
I'm not sure if this change warrants a version number increase, instead of a build number increase - happy to adjust as needed.

**Comment by hoechenberger** [comment]
> I'm not sure if this change warrants a version number increase, instead of a build number increase - happy to adjust as needed.

I'd say bump the version number to 1.4 and reset the build number to 0 :)

**Comment by pauldmccarthy** [comment]
> I'd say bump the version number to 1.4 and reset the build number to 0 :)

Done!

**Review by hoechenberger — APPROVED** [review]
Looks good to me! Let's wait for the other reviewers to share their opinion ...

**Comment by ChrisBarker-NOAA** [comment]
Have you tested this? I recall that it was deliberate to put a copy, rather than a soft link, in the bundle.

Apple requires that the executable be inside an app bundle in order to access the Window manager, so I don't hink an soft link will work.

Maybe something's changed, but let's make sure.

**Comment by pauldmccarthy** [comment]
@ChrisBarker-NOAA Just replied [here](https://github.com/conda-forge/python.app-feedstock/issues/25#issuecomment-1009260963) :)

**Comment by ChrisBarker-NOAA** [comment]
me too -- sorry for the noise -- carry on!

Would you like me to merge?

**Comment by hoechenberger** [comment]
Thank you, @pauldmccarthy!!

**Comment by pauldmccarthy** [comment]
No problem!

In case a unit test is desired in the future, I just came aross [this snippet](https://github.com/Nuitka/Nuitka/issues/799#issuecomment-916985437).

I think that simply attempting to call [`GetCurrentProcess`](https://developer.apple.com/documentation/applicationservices/1501115-getcurrentprocess?language=objc) is enough to determine whether we are running a Framework build. It is deprecated, but I can't find any information about a suitable replacement (possibly https://developer.apple.com/documentation/foundation/nsprocessinfo).

**Comment by pauldmccarthy** [comment]
Another thought: if sym-linking does end up being a problem in a future version of macOS, this recipe could easily be re-worked to use a wrapper script instead of a sym-link, e.g. `$PREFIX/python.app/Contents/MacOS/python` could simply be a script containing:

```
#!/usr/bin/env bash
thisdir=$(cd $(dirname $0) && pwd)
${thisdir}/../../../bin/python "$@"
```

**Comment by hoechenberger** [comment]
@pauldmccarthy 
Let's wait a few weeks and see if any complaints come in about the new release. If everything seems to keep on working fine, we can make this adjustment you proposed. WDYT?

btw feel free to make a PR to add yourself to the feedstock maintainers!
(You need to edit the respective section in the recipe and then re-render the feedstock)

**Comment by hoechenberger** [comment]
@pauldmccarthy Oh and a test case would certainly be very welcome!

**Comment by pauldmccarthy** [comment]
@hoechenberger No problem, I'll try and come back to this in a few days :+1:

**Pull request merged**
