### PR TITLE
PR: Support automatic graphic switching

### PR DESCRIPTION
**Pull request by steff456**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This change is necessary for not forcing discrete graphics on OSX, this was an issue reported in Spyder.
cc @ccordoba12

### CODE REVIEW

**Review by hoechenberger — APPROVED** [review]

**Comment by ccordoba12** [comment]
Thanks for your help @steff456!

Pinging @anaconda-pkg-build about this one, so they can pick up the fix on defaults.

**Comment by ccordoba12** [comment]
@conda-forge/core, could you merge this one? It was already approved by one of the feedstock maintainers, so I think it's good to go.

**Comment by msarahan** [comment]
Ideally the feedstock maintainers should merge things when they approve of them. I will do so now, but can't do anything to support this if it goes wrong.

**Comment by hoechenberger** [comment]
Thanks for merging, @msarahan!

**Comment by ccordoba12** [comment]
Thanks @msarahan!

Pinging @anaconda-pkg-build again about this one. This will make Spyder (or any other app that depends on `python.app`) to automatically switch the graphics card at startup.

**Comment by mingwandroid** [comment]
Thanks Carlos, I'll try to get something ready later for this.

**Comment by ccordoba12** [comment]
Thanks Ray!

**Pull request merged**
